# Generated by Django 3.1.5 on 2021-02-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores_shell_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='notes',
            new_name='notas',
        ),
    ]
