# Generated by Django 3.1.5 on 2021-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_autores_shell_app', '0002_auto_20210204_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notas',
            field=models.TextField(),
        ),
    ]
